{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPULA 1/5/15",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    },
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    },
    {
     "expr": "100 - \n(avg(rate(node_cpu_seconds_total{mode=\"idle\"}[15m])) * 100)"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[2m])) * 100)"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_avail_bytes{mountpoint=\"/\"}) - node_filesystem_size_bytes{mountpoint=\"/\"}) * -1"
    }
   ]
  }
 ]
}